=== gmhumber/blitztech/XML/users.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="userId" type="xs:positiveInteger" />
                            <xs:element name="password" type="xs:string" />
                            <xs:element name="name">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="firstName" type="xs:string" />
                                        <xs:element name="lastName" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="address" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="street" type="xs:string" />
                                        <xs:element name="city" type="xs:string" />
                                        <xs:element name="province" type="xs:string" />
                                        <xs:element name="country" type="xs:string" />
                                        <xs:element name="postalCode" type="postalCode" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="email" type="email" />
                            <xs:element name="phone" type="phone" minOccurs="0" />
                            <xs:element name="privilages" type="privilages" />
                            <xs:element name="userClass" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- Custom Data Types -->
    <xs:simpleType name="postalCode">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z]\d[a-zA-Z]\d[a-zA-Z]\d" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="email">
        <xs:restriction base="xs:string">
            <xs:pattern value="[\w\.\-]+@[\w\.\-]+" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="phone">
        <xs:restriction base="xs:string">
            <xs:pattern value="\(\d{3}\)\d{3}\-\d{4}" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="privilages">
        <xs:restriction base="xs:string">
            <xs:enumeration value="user"/>
            <xs:enumeration value="admin" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== gmhumber/blitztech/XML/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="users.xsd">
<!-- All passwords are Bcrypt hashes of the string: "Test123" -->
    <user>
        <userId>1</userId>
        <password>$2y$10$O6rMQi5Okc1Sq2hZtvtlI.jNo8Tzq.2VEFmUkIUcbTfdOnFHyUNA2</password>
        <name>
            <firstName>Chris</firstName>
            <lastName>Krebs</lastName>
        </name>
        <email>ckrebs@blitztech.ca</email>
        <phone>(416)555-8989</phone>
        <privilages>admin</privilages>
        <userClass>support</userClass>
    </user>
    <user>
        <userId>2</userId>
        <password>$2y$10$O6rMQi5Okc1Sq2hZtvtlI.jNo8Tzq.2VEFmUkIUcbTfdOnFHyUNA2</password>
        <name>
            <firstName>Joe</firstName>
            <lastName>Schmo</lastName>
        </name>
        <email>jschmo@gmail.com</email>
        <privilages>user</privilages>
        <userClass>customer</userClass>
    </user>
    <user>
        <userId>3</userId>
        <password>$2y$10$O6rMQi5Okc1Sq2hZtvtlI.jNo8Tzq.2VEFmUkIUcbTfdOnFHyUNA2</password>
        <name>
            <firstName>Betty</firstName>
            <lastName>Boop</lastName>
        </name>
        <address>
            <street>65 Main St.</street>
            <city>Toronto</city>
            <province>Ontario</province>
            <country>Canada</country>
            <postalCode>M7E0P4</postalCode>
        </address>
        <email>bettyb@aol.com</email>
        <phone>(647)555-4567</phone>
        <privilages>user</privilages>
        <userClass>customer</userClass>
    </user>
</users>
